name: Win64

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

env:
  zef_fetch_degree: 4
  zef_test_degree: 2
  # saving a few characters on the default C:\Users\RUNNER~1\AppData\Local\Temp trying to avoid the 260 chars
  # max path length limit of Windows
  # https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#maximum-path-length-limitation
  TEMP: 'D:\T'
  TMP: 'D:\T'
  ZEF_CONFIG_TEMPDIR: 'D:\T'

jobs:
  raku:
    strategy:
      matrix:
        os:
          - windows-latest
        raku-version:
          - 'latest'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Windows LongPathsEnabled and short TEMP path
        run: |
          New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force
          mkdir -Force "${{ env.TEMP }}"

      - uses: actions/checkout@v3
      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}
      - name: Install Dependencies
        run: |
          choco install xclip
          zef install --/test --deps-only .
          zef install --/test App::Prove6
      - name: Run Tests
        run: |
          raku -I. t/01-copy-to-clipboard.t
          raku -I. t/02-from-clipboard.t
          raku -I. t/03-synonyms.t
#      - name: Run prove6
#        run: prove6 -l t
